### ISSUE TITLE
[ENHANCEMENT] Minimize informations on screen 

### ISSUE THREAD

**Issue by RoiArthurB** [project-SIMPLE/GamaServerMiddleware#11]
Views are built with components, but those components don't need to be displayed all the time. 

E.g, if no headsets are connected to the middleware, do not display the title "Headset connected:"

![image](https://github.com/user-attachments/assets/306925ed-606e-4edb-b46d-f218b355ff68)

---

This issue is a general remark to hide and keep the interface with as little informations (i.e the one necessary for the view only) as possible to not loose users.

**Comment by nautuan** [comment]
done
