### ISSUE TITLE
Add multi-languages support

### ISSUE THREAD

**Issue by RoiArthurB** [project-SIMPLE/GamaServerMiddleware#19]
Even if there's not much text, it could be great to start adding a multi-language support.

In the idea, this feature would require implementing some parts : 
- Implementing a multi-language library (there's a lot existing, no preferences)
  - In general, those rely on storing every text string in one json file per language (eg. `i18n`). Not very complicated to use 
- Edit all the text (both in prod and dev mode)
- Add a language selector in the UI
- Documenting this part in the wiki ;)

**Comment by nautuan** [comment]
Done
