### ISSUE TITLE
Write a first version of the user documentation of the platform v2

### ISSUE THREAD

**Issue by RoiArthurB** [project-SIMPLE/GamaServerMiddleware#2]
The platform evolved a lot since the v1, a lot changed under the hood, on the interface and on how to set it up.

To ease the early use of it, we need a short/simplified documentation explaining how to install it and run it on people's computer.

**Comment by nautuan** [comment]
Added page on wiki: Launching V2

**Comment by nautuan** [comment]
Added page Monitor Webpage V2
