### ISSUE TITLE
[BUG] Wrong GAMA monitoring when closing running simulation

### ISSUE THREAD

**Issue by RoiArthurB** [project-SIMPLE/GamaServerMiddleware#6]
## Describe the issue

Currently, if you start a simulation, pause it and **then** end it, everything's fine
But ! If you start a simulation run it and (while it's running) end it; GAMA properly close the simulation but view think that the simulation is only in pause (and not closed)

## Step to reproduce

- Select a Learning Package
- Connect GAMA
- Start simulation
- Resume it (run it)
- End the simulation (without pausing it)
- See the bug

## What to do

Properly handling case while closing the simulation without pausing it

**Comment by nautuan** [comment]
Bug Fixed
