### ISSUE TITLE
[ENHANCEMENT] Use CMS splashscreen

### ISSUE THREAD

**Issue by RoiArthurB** [project-SIMPLE/GamaServerMiddleware#9]
Within the `settings.json` of each learning package (used by the CMS) is referenced an option `splashscreen` to customize a little the option but is never used

## What to do

Try to find an aesthetic way to get this image to skin the current white rectangle of model's selection.

**Comment by nautuan** [comment]
done

**Comment by RoiArthurB** [comment]
Love the design of it !

![image](https://github.com/user-attachments/assets/100a9627-2b96-461a-a118-9566fe73f1ac)

The splashscreen image should come from the package's folder (as it'll be the only part updated/added in the application)

**Comment by nautuan** [comment]
done
